version: "3.9"

services:
  stealth-beholder:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: stealth-beholder

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./output:/app/outputs

    working_dir: /app

    command: python main.py
