version: "3.9"

services:
  stealth-beholder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: stealth-beholder

    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../output:/app/outputs

    working_dir: /app

    command: python src/train.py
